# One-off generator for issue #23 skill pack (run from repo root).
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$skillsRoot = Join-Path $root ".grok\skills"

$wiki = "https://discworld.starturtle.net/"
$official = "https://www.discworldmud.org/"

function New-Skill($dir, $name, $desc, $title, $surfaces, $locked, $unknown) {
  $path = Join-Path $skillsRoot $dir
  New-Item -ItemType Directory -Force -Path $path | Out-Null
  $lockedBullets = ($locked | ForEach-Object { "- $_" }) -join "`n"
  $unknownBullets = ($unknown | ForEach-Object { "- $_" }) -join "`n"
  $body = @"
---
name: $name
description: >
  $desc
---

# $title

Companion to ``mud-skill`` and ``discworld-mud``. Surfaces: **$surfaces** (issue #23).
Public facts only  - link-out [$wiki]($wiki) and [$official]($official).
Does not stamp ready for human UAT. No invented host, port, or credentials.

## LOCKED

$lockedBullets

## UNKNOWN

$unknownBullets
"@
  Set-Content -Path (Join-Path $path "SKILL.md") -Value $body -Encoding UTF8
}

# Cities (10)
New-Skill "discworld-city-ankh-morpork" "discworld-city-ankh-morpork" "Discworld MUD city guide for Ankh-Morpork: locations, shops, guilds, lore. Use when the user says AM, Ankh-Morpork, city guide." "Ankh-Morpork (city guide)" "city, location, shop, guild, lore" @("Ankh-Morpork is the largest city hub for many players; streets vary in lighting and danger (public newbie material).", "Load ``discworld-ankh-survival`` for first-10-minute ritual before deep exploration.", "Navigate using exits shown in game text; do not invent room or shop ENAMEs.", "Operator supplies connection details only.") @("Per-street shop lists and quest NPC rooms  - confirm in game.")
New-Skill "discworld-city-lancre" "discworld-city-lancre" "Discworld MUD city and region guide for Lancre and the Ramtops: location, lore, witch themes. Use for Lancre, Ramtops." "Lancre and Ramtops (city guide)" "city, location, lore" @("Lancre region ties to witch and countryside themes from public Discworld MUD docs.", "Travel between areas follows in-game exits and conveyance shown to the player.", "Human-in-the-loop before long wilderness hunts.") @("Exact guildhouses and shop names  - read from game.")
New-Skill "discworld-city-djelibeybi" "discworld-city-djelibeybi" "Discworld MUD city guide for Djelibeybi: location, desert lore, warrior guard themes." "Djelibeybi (city guide)" "city, location, lore" @("Djelibeybi is a desert kingdom on the Disc with public MUD coverage (wiki orientation).", "Warrior specialisation Djelian Guard is named in public warrior newbie docs.", "Respect heat, water, and NPC law cues from game text.") @("Shop stock and temple layouts  - in-game only.")
New-Skill "discworld-city-klatch" "discworld-city-klatch" "Discworld MUD city guide for Klatch and Klatchian areas: location, lore, travel." "Klatch (city guide)" "city, location, lore" @("Klatch is a major Discworld nation with coastal and desert ties in Pratchett canon; MUD has Klatch-facing content (wiki).", "Use ``discworld-mud`` for guild choice before cross-continent trips.") @("Instance-specific room graph  - never guess.")
New-Skill "discworld-city-bes-pelargic" "discworld-city-bes-pelargic" "Discworld MUD city guide for Bes Pelargic and Agatean themes: location, lore." "Bes Pelargic (city guide)" "city, location, lore" @("Bes Pelargic is the Agatean empire port/city area on Discworld MUD (public wiki pages).", "Long-distance travel may need human-approved time and supplies.") @("Local guild access and visa/quest gates  - game text only.")
New-Skill "discworld-city-genua" "discworld-city-genua" "Discworld MUD city guide for Genua: location, voodoo and carnival lore." "Genua (city guide)" "city, location, lore" @("Genua maps to Caribbean/voodoo Discworld themes; MUD wiki documents the area at high level.", "Treat unfamiliar NPC magic as risky until ``consider`` and human OK.") @("Carnival quests and hidden zones  - harvest per run.")
New-Skill "discworld-city-sto-lat" "discworld-city-sto-lat" "Discworld MUD city guide for Sto Lat: location, nearby Sto Plains travel." "Sto Lat (city guide)" "city, location" @("Sto Lat is a stoic plains city near Ankh-Morpork in canon; playable on the MUD (wiki).", "Good mid-game hub for some guild errands per public guides.") @("Exact distance routes and tolls  - from game.")
New-Skill "discworld-city-ephebe" "discworld-city-ephebe" "Discworld MUD city guide for Ephebe: location, philosopher and desert coast lore." "Ephebe (city guide)" "city, location, lore" @("Ephebe is the Disc's philosopher city (Greek parody); appears in MUD geography (wiki).", "Ask human before PvP or theft in foreign cities.") @("Temple and arena details  - in-game.")
New-Skill "discworld-city-pseudopolis" "discworld-city-pseudopolis" "Discworld MUD city guide for Pseudopolis: location and travel links." "Pseudopolis (city guide)" "city, location" @("Pseudopolis is a major Disc city (home of Eric in canon); referenced on MUD wiki.", "Use umbrella navigate procedure for unfamiliar exits.") @("Newbie-friendly shops  - confirm live.")
New-Skill "discworld-city-uberwald" "discworld-city-uberwald" "Discworld MUD region guide for Uberwald: vampires, werewolves, location lore." "Uberwald (region guide)" "city, location, lore" @("Uberwald is the Disc's Eastern Europe analogue with undead themes; MUD has Uberwald areas (public docs).", "Night travel and supernatural NPCs warrant caution and human OK for combat.") @("Castle and clan quest lines  - spoiler-sensitive; harvest in session.")

# Guilds (7)
New-Skill "discworld-guild-warrior" "discworld-guild-warrior" "Discworld MUD warrior guild playbook: fighting, weapons, specialisations. Use for warrior guild, berserker, guard specials." "Warriors' Guild" "guild, fight, weapon" @("Warriors teach combat skills; specialisation is chosen at join (public ``warrior_specialisations`` newbie doc).", "Examples include Palace Guard and Weapon Masters' Court in AM, Djelian Guard, Samurai, Lancre Highland Regiment (link-out in ``discworld-mud``).", "Train at guild teachers shown in game; ``skills fighting`` lists primaries.", "Greg newbie combat area is public FAQ practice (see ``discworld-fight-newbie-greg``).") @("Optimal weapon pairs per spec  - character-specific.")
New-Skill "discworld-guild-wizard" "discworld-guild-wizard" "Discworld MUD wizard guild: spells, magic, university themes. Use for wizard guild, spells, unseen." "Wizards' Guild" "guild, lore, fight" @("Wizards use spell slots and guild libraries per public newbie wizard docs.", "Unseen University themes tie to Ankh-Morpork (``discworld-location-am-unseen-university``).", "Do not spam high-risk spells in city streets without human OK.") @("Spell progression costs and quest gates  - in-game.")
New-Skill "discworld-guild-witch" "discworld-guild-witch" "Discworld MUD witch guild: herbs, headology, flying. Use for witch guild, female character join rules." "Witches' Guild" "guild, lore, fight" @("Witch magic is herbs, cursing, flying, headology  - not wizard slots (public witches_guild doc).", "Public guild description: female characters only for join.", "See expanded steps in ``discworld-mud`` witch playbook.") @("Coven and mentor routes  - harvest per character.")
New-Skill "discworld-guild-thief" "discworld-guild-thief" "Discworld MUD thief guild: stealing, fencing, Ankh street crime. Use for thief guild, steal, fence." "Thieves' Guild" "guild, fight, shop" @("Thieves' Guild is legalised theft in Ankh-Morpork canon; MUD has thief skills and rules (wiki/newbie).", "Ask human before stealing from players or unique NPCs.", "Fence loot only at game-identified fences.") @("Guild quota and licence mechanics  - read help in game.")
New-Skill "discworld-guild-priest" "discworld-guild-priest" "Discworld MUD priest guild: gods, rituals, healing and combat faith skills." "Priests' Guild" "guild, lore, fight" @("Priests serve Discworld gods with rituals and faith points (public priest newbie material).", "Patron deity choice is a major decision  - human confirms before join.", "Respect temple NPCs and ``rituals`` help from game.") @("Per-god spell lists  - deity-specific.")
New-Skill "discworld-guild-assassin" "discworld-guild-assassin" "Discworld MUD assassin guild: contracts, stealth, Ankh guild school." "Assassins' Guild" "guild, fight, lore" @("Assassins' Guild is in Ankh-Morpork in canon; MUD covers contracts and PvP rules in public docs.", "Human must approve any player contract or lethal PvP.", "Stealth and poison skills are guild-taught (game text).") @("Contract board procedures  - in-game only.")
New-Skill "discworld-guild-fool" "discworld-guild-fool" "Discworld MUD fool guild: jesting, entertainment, low combat focus." "Fools Guild" "guild, lore" @("Fool is one of seven working guilds on Discworld MUD (issue #12 table).", "Roleplay-heavy; combat is not the primary path (public orientation).", "Confirm character intent with human before join  - hard to unwind.") @("Skill progression and quest gags  - wiki sparse; harvest in play.")

# Fighting (6)
New-Skill "discworld-fight-combat-basics" "discworld-fight-combat-basics" "Discworld MUD fighting guide: combat flow, kill, loot gates. Use for combat basics, fight, kill NPC." "Combat basics" "fight, weapon" @("Use ``kill`` / combat verbs only with human OK for risky targets.", "Read ``consider`` output before attacking (see ``discworld-fight-consider``).", "Loot only when rules and human allow; no unique quest item drops without OK.") @("Exact damage formulae  - not needed for playbooks.")
New-Skill "discworld-fight-wimpy-flee" "discworld-fight-wimpy-flee" "Discworld MUD fighting guide: wimpy, flee, survival in combat." "Wimpy and flee" "fight" @("Set ``wimpy`` to auto-flee at low HP (public combat help).", "``flee`` toward known safe exits; in AM prefer lit streets (``discworld-ankh-survival``).", "Stop combat if game shows illegality (guards, divine smite).") @("Optimal wimpy thresholds  - tune per character.")
New-Skill "discworld-fight-consider" "discworld-fight-consider" "Discworld MUD fighting guide: consider targets before combat." "Consider" "fight" @("``consider`` estimates difficulty vs your skills (public combat doc).", "Repeat after equipment or skill changes.", "If consider warns of death, get human approval or skip.") @("Colour codes and exact tiers  - read live output.")
New-Skill "discworld-fight-newbie-greg" "discworld-fight-newbie-greg" "Discworld MUD newbie combat training with Greg: practice fights." "Newbie combat (Greg)" "fight" @("Official FAQ describes Greg in the newbie combat area for practice.", "Answer his prompt; sobriety matters for training.", "Leave when asked; training rate slows over time.") @("Room path from your spawn  - follow signs in game.")
New-Skill "discworld-fight-tactics" "discworld-fight-tactics" "Discworld MUD fighting guide: tactics, combat options, attitude." "Tactics and options" "fight" @("``options combat`` and ``tactics`` adjust combat attitude (public help).", "Match tactics to weapon type and guild (warrior vs thief).", "Human OK before switching to aggressive tactics in cities.") @("Best tactic per boss  - encounter-specific.")
New-Skill "discworld-fight-skills-advance" "discworld-fight-skills-advance" "Discworld MUD fighting guide: fighting skills, advance, teachers." "Fighting skills and advance" "fight, guild" @("``skills fighting`` lists combat-related skills.", "Use guild teachers or NPC trainers shown in game for ``advance``.", "Ask human before large XP spends.") @("Primary vs secondary skill caps  - guild-specific.")

# Weapons (5)
New-Skill "discworld-weapon-swords" "discworld-weapon-swords" "Discworld MUD weapon guide: swords and fencing skills, shops." "Swords" "weapon, shop, fight" @("Sword-family weapons use sword/fencing skills (public weapon help).", "Buy from weapon shops identified in game (``discworld-shop-weapons``).", "Weight affects combat  - check encumbrance (``discworld-weapon-armour-encumbrance``).") @("Best sword per spec  - character build.")
New-Skill "discworld-weapon-axes" "discworld-weapon-axes" "Discworld MUD weapon guide: axes and heavy blades." "Axes" "weapon, fight" @("Axes use axe skills; often warrior-favoured in public guides.", "Two-handed vs one-handed affects tactics and shield use.") @("Named artefact axes  - quest spoilers; in-game.")
New-Skill "discworld-weapon-polearms" "discworld-weapon-polearms" "Discworld MUD weapon guide: polearms, spears, halberds." "Polearms" "weapon, fight" @("Polearms include spears and halberds per weapon help.", "Reach weapons suit some warrior specs (UNKNOWN per build).") @("Shop availability by city  - confirm locally.")
New-Skill "discworld-weapon-thrown" "discworld-weapon-thrown" "Discworld MUD weapon guide: thrown weapons and ranged combat." "Thrown and ranged" "weapon, fight" @("Thrown weapons use appropriate fighting skills from help files.", "Ammo and retrieval  - loot or buy per game rules.") @("Assassin thrown builds  - guild-specific.")
New-Skill "discworld-weapon-armour-encumbrance" "discworld-weapon-armour-encumbrance" "Discworld MUD weapon and armour guide: burden, encumbrance, score." "Armour and encumbrance" "weapon, fight, shop" @("Heavy armour and weapons reduce dodge and increase burden (public score/inventory guidance).", "Balance weapon skill with defence skill training.", "Repair armour at game-shown smiths or shops.") @("Optimal armour sets  - level-dependent.")

# Shops (5)
New-Skill "discworld-shop-weapons" "discworld-shop-weapons" "Discworld MUD shop guide: weapon shops, buy and sell weapons." "Weapon shops" "shop, weapon" @("Buy weapons only from NPC shops named in room text.", "Compare weight and skill requirements before purchase.", "Ask human before expensive or unique purchases.") @("AM vs Lancre price lists  - live economy.")
New-Skill "discworld-shop-armour" "discworld-shop-armour" "Discworld MUD shop guide: armour shops and protection gear." "Armour shops" "shop, weapon" @("Armour types map to coverage and burden; read item descriptions in game.", "Thieves may need light armour  - guild help.") @("Shield vendors by city  - in-game.")
New-Skill "discworld-shop-general" "discworld-shop-general" "Discworld MUD shop guide: general stores, food, containers." "General shops" "shop, location" @("General stores sell food, containers, and misc supplies (wiki lists at high level).", "Food and drink affect sobriety and some guild mechanics.") @("Exact item ENAMEs  - never invent.")
New-Skill "discworld-shop-magic-components" "discworld-shop-magic-components" "Discworld MUD shop guide: magic components, herbs, witch and wizard supplies." "Magic and component shops" "shop, guild, lore" @("Wizards and witches buy components from appropriate shops (guild newbie docs).", "Herb gathering may supplement shops for witches (in-game ``gather`` help).") @("Rare component locations  - quest content.")
New-Skill "discworld-shop-pawn-trade" "discworld-shop-pawn-trade" "Discworld MUD shop guide: pawn, trade, sell loot safely." "Pawn and trade" "shop" @("Sell mundane loot at pawn or general traders shown in game.", "Do not sell quest or unique items without human check.", "Thieves use fences for stolen goods per guild rules.") @("Best sell prices  - city-dependent.")

# Lore (5)
New-Skill "discworld-lore-death" "discworld-lore-death" "Discworld MUD lore guide: Death, afterlife, mort rituals." "Death and afterlife (lore)" "lore" @("Death personification is core Discworld canon; MUD respects Death NPC tropes.", "Losing items or corpses follows game rules  - read death message carefully.", "No real-world harm; roleplay tone.") @("Speed of corpse decay and retrieval  - game mechanics.")
New-Skill "discworld-lore-gods-patrons" "discworld-lore-gods-patrons" "Discworld MUD lore guide: gods, priests, patron choice." "Gods and patrons (lore)" "lore, guild" @("Many Disc gods exist; priests choose patrons (public priest docs).", "Temples are city landmarks  - find via game not invented names.") @("Full god spell trees  - in-game help only.")
New-Skill "discworld-lore-races-species" "discworld-lore-races-species" "Discworld MUD lore guide: playable species and racial traits." "Races and species (lore)" "lore" @("Character creation species affect stats and some guild gates (wiki character creation).", "Witch join restriction for male characters is guild-specific not species-wide (verify score).") @("Per-race quest lines  - harvest.")
New-Skill "discworld-lore-books-tiffany" "discworld-lore-books-tiffany" "Discworld MUD lore guide: book references, Tiffany Aching, witches lore." "Book lore (witches and Tiffany)" "lore, guild" @("Lancre and witch play echo Pratchett witch books at high level.", "Use lore for roleplay tone, not for inventing puzzle solutions.") @("Quest text tied to specific books  - spoiler.")
New-Skill "discworld-lore-guild-politics" "discworld-lore-guild-politics" "Discworld MUD lore guide: guild rivalry, city law, watch." "Guild politics and law (lore)" "lore, guild, city" @("Ankh-Morpork has Watch and guild legal structures in canon.", "Illegal acts risk guards and fines  - heed game messages.") @("Player org politics  - live server.")

# Locations (8)
New-Skill "discworld-location-am-guild-quarter" "discworld-location-am-guild-quarter" "Discworld MUD location guide: Ankh-Morpork guild quarter and recruiters." "AM guild quarter (location)" "location, guild, city" @("Major guildhouses cluster in AM; find recruiters via signs and ``look``.", "Pair with ``discworld-ankh-survival`` for first approach.") @("Exact map coordinates  - use in-game maps.")
New-Skill "discworld-location-am-docks" "discworld-location-am-docks" "Discworld MUD location guide: Ankh-Morpork docks and sea travel." "AM docks (location)" "location, city" @("Docks connect to sea travel and smuggling themes in canon.", "Human OK before boarding ships or entering dangerous waterfront rooms.") @("Sailing schedules  - game text.")
New-Skill "discworld-location-am-sewers" "discworld-location-am-sewers" "Discworld MUD location guide: Ankh-Morpork sewers  - high risk location." "AM sewers (location)" "location, city, fight" @("Sewers are dangerous; avoid in first 10 minutes (``discworld-ankh-survival``).", "Bring light, wimpy, and escape route if human orders sewer run.") @("Monster levels and quest nodes  - live.")
New-Skill "discworld-location-am-unseen-university" "discworld-location-am-unseen-university" "Discworld MUD location guide: Unseen University and wizard areas in AM." "Unseen University (location)" "location, city, guild, lore" @("UU is wizard cultural centre in Ankh-Morpork (canon + MUD).", "Non-wizards: respect access rules shown by guards and doors.") @("Library quest permissions  - in-game.")
New-Skill "discworld-location-lancre-kaup" "discworld-location-lancre-kaup" "Discworld MUD location guide: Lancre countryside and Kaup area." "Lancre countryside (location)" "location, city" @("Ramtop countryside has farms, forests, and witch-adjacent zones (wiki).", "Weather and wilderness combat differ from city.") @("Hidden paths  - explore with human OK.")
New-Skill "discworld-location-hub-rose-garden" "discworld-location-hub-rose-garden" "Discworld MUD location guide: central hubs, rose garden, meeting spots." "Hubs and rose garden (location)" "location, lore" @("Players meet at known hubs; rose garden is a common reference on wiki for orientation.", "Good place to ask newbie questions if human approves channels.") @("Current player gatherings  - live.")
New-Skill "discworld-location-bad-ass-cottage" "discworld-location-bad-ass-cottage" "Discworld MUD location guide: Bad Ass and Granny Weatherwax cottage lore." "Bad Ass cottage (location)" "location, lore" @("Bad Ass is Lancre village from canon; MUD may include related zones (wiki).", "Treat powerful NPC witches with respect.") @("Quest triggers  - in-game.")
New-Skill "discworld-location-roundworld-connection" "discworld-location-roundworld-connection" "Discworld MUD location guide: Roundworld and easter-egg areas." "Roundworld connections (location)" "location, lore" @("Discworld canon includes Roundworld links; MUD may have easter-egg areas (public wiki mentions).", "Spoiler-sensitive; human opts in.") @("Access requirements  - quest-locked.")

$count = (Get-ChildItem (Join-Path $skillsRoot "*/SKILL.md")).Count
Write-Output "SKILL.md count: $count"
